import type { Metadata } from "next";
import "./globals.css";
import logo from '../../public/logo.svg'
import { Happy_Monkey } from 'next/font/google'

const font = Happy_Monkey({
  weight: "400",
  subsets: ["latin"]
})


export const metadata: Metadata = {
  title: "Auto-Bowl",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>{children}</body>
    </html>
  );
}
